-- Prepare for Data Migration (UPDATED)
-- 1. Create ALL missing tables from the original schema
-- 2. Disable RLS temporarily to allow bulk insert

-- Enable Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- --- MISSING TABLES CREATION ---

-- 1. saved_articles
CREATE TABLE IF NOT EXISTS saved_articles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    article_id UUID REFERENCES articles(id) ON DELETE CASCADE,
    saved_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    notes TEXT,
    UNIQUE(user_id, article_id)
);

-- 2. user_activity_log
CREATE TABLE IF NOT EXISTS user_activity_log (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    article_id UUID REFERENCES articles(id) ON DELETE CASCADE,
    action VARCHAR(20) NOT NULL CHECK (action IN ('view', 'click', 'save', 'like', 'dislike', 'share')),
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. newsletters
CREATE TABLE IF NOT EXISTS newsletters (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    sent_at TIMESTAMP WITH TIME ZONE,
    articles UUID[] DEFAULT '{}',
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. article_scores
CREATE TABLE IF NOT EXISTS article_scores (
    article_id UUID REFERENCES articles(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    score NUMERIC(5,2) NOT NULL,
    calculated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (article_id, user_id)
);

-- 5. daily_messages
CREATE TABLE IF NOT EXISTS daily_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    date DATE NOT NULL UNIQUE,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. jt_backgrounds
CREATE TABLE IF NOT EXISTS jt_backgrounds (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    lieu TEXT,
    prompt TEXT,
    image_url TEXT,
    presenter_id UUID, -- Foreign key added later or here if table exists
    numero INTEGER,
    presenter_script TEXT,
    is_generated BOOLEAN DEFAULT false,
    airtable_id TEXT UNIQUE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. photo_avatar_personnalite
CREATE TABLE IF NOT EXISTS photo_avatar_personnalite (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    numero INTEGER,
    nom TEXT,
    genre TEXT,
    status TEXT,
    contribution TEXT,
    image_url TEXT,
    airtable_id TEXT UNIQUE,
    generated BOOLEAN DEFAULT false,
    is_female BOOLEAN,
    is_alive BOOLEAN DEFAULT true
);

-- 8. planning_cours
CREATE TABLE IF NOT EXISTS planning_cours (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    google_event_id TEXT UNIQUE,
    title TEXT NOT NULL,
    description TEXT,
    start_date TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date TIMESTAMP WITH TIME ZONE,
    location TEXT,
    detected_topic TEXT,
    external_resources JSONB,
    generated_prompt TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    organizer_email TEXT
);

-- 9. system_prompts
CREATE TABLE IF NOT EXISTS system_prompts (
    id TEXT PRIMARY KEY,
    content TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 10. tutorials (Already in previous script, included for completeness)
CREATE TABLE IF NOT EXISTS tutorials (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    channel_name TEXT,
    url TEXT NOT NULL UNIQUE,
    software TEXT,
    airtable_id TEXT,
    image_url TEXT
);

-- 11. app_messages (Already in previous script)
CREATE TABLE IF NOT EXISTS app_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    type TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    active BOOLEAN DEFAULT true
);

-- --- DISABLE RLS ---

ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE sources DISABLE ROW LEVEL SECURITY;
ALTER TABLE articles DISABLE ROW LEVEL SECURITY;
ALTER TABLE daily_news_videos DISABLE ROW LEVEL SECURITY;
ALTER TABLE tutorials DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles DISABLE ROW LEVEL SECURITY;

-- Now these tables definitely exist, so we can verify and disable RLS
ALTER TABLE saved_articles DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_activity_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE newsletters DISABLE ROW LEVEL SECURITY;
ALTER TABLE article_scores DISABLE ROW LEVEL SECURITY;
ALTER TABLE daily_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE jt_backgrounds DISABLE ROW LEVEL SECURITY;
ALTER TABLE photo_avatar_personnalite DISABLE ROW LEVEL SECURITY;
ALTER TABLE planning_cours DISABLE ROW LEVEL SECURITY;
ALTER TABLE system_prompts DISABLE ROW LEVEL SECURITY;

-- End of Prep Script
